stage('Aqua Reports') {

    environment {
        AQUA_URL = @AQUA_URL@
        AQUA_PROJECT_ID = @AQUA_PROJECT_ID@
        AQUA_PRODUCT_ID = @AQUA_PRODUCT_ID@
        AQUA_RELEASE = @AQUA_RELEASE@
        AQUA_LEVEL = @AQUA_LEVEL@
        AQUA_JUNIT_TEST_FOLDER_ID = @AQUA_JUNIT_TEST_FOLDER_ID@
        AQUA_INTEGRATION_TEST_FOLDER_ID = @AQUA_INTEGRATION_TEST_FOLDER_ID@
    }

    parallel {
@STAGES@
    }
}
